### ISSUE TITLE
React DeckGL not handling async data

### ISSUE THREAD

**Issue by arraydude** [uber/deck.gl#4198]
#### Description
Using data from an URL the React DeckGL won't show anything.

#### Repro Steps

Having this JSON: 
```json
{"initialViewState": {"bearing": -27.36, "latitude": 52.2323, "longitude": -1.415, "maxZoom": 15, "minZoom": 5, "pitch": 40.5, "zoom": 6}, "layers": [{"@@type": "HexagonLayer", "autoHighlight": true, "coverage": 1, "data": "https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv", "elevationRange": [0, 3000], "elevationScale": 50, "extruded": true, "getPosition": "@@=[lng, lat]", "id": "b4e04719-ba90-4bb8-b429-1aac478539ac", "pickable": true}], "mapStyle": "mapbox://styles/mapbox/light-v9", "views": [{"@@type": "MapView", "controller": true}]}
```

Given the JSON above, when we pass it into jsonConverter like this...
```javascript
import { JSONConverter } from "@deck.gl/json"
import * as layers from "@deck.gl/layers"
import * as aggregationLayers from "@deck.gl/aggregation-layers"
const configuration = {
  classes: Object.assign({}, layers, aggregationLayers),
}
const jsonConverter = new JSONConverter({ configuration })
const deck = jsonConverter.convert(json)
```

...we get the following deck object:
```
initialViewState:
  bearing: -27.36
  latitude: 52.2323
  longitude: -1.415
  maxZoom: 15
  minZoom: 5
  pitch: 40.5
  zoom: 6
  __proto__: Object
layers: Array(1)
  0: HexagonLayer
    isComposite: (...)
    stats: (...)
    props:
      data: Array(0)
      autoHighlight: true
      coverage: 1
      elevationRange: (2) [0, 3000]
      elevationScale: 50
      extruded: true
      getPosition: ƒ func(row)
      id: "c83a8051-afff-4750-8c57-713c47831e63"
      pickable: true
      _component: HexagonLayer
        isComposite: (...)
        stats: (...)
        props: {autoHighlight: true, coverage: 1, elevationRange: Array(2), elevationScale: 50, extruded: true, …}
        id: "c83a8051-afff-4750-8c57-713c47831e63"
        count: 5
        lifecycle: "Awaiting state"
        parent: null
        context: null
        state: null
        internalState: null
        __proto__: CompositeLayer
    _asyncPropOriginalValues:
      data: "https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv"
      __proto__: Object
    _asyncPropResolvedValues:
      __proto__: Object
    __proto__: Object
    id: "c83a8051-afff-4750-8c57-713c47831e63"
    count: 5
    lifecycle: "Awaiting state"
    parent: null
    context: null
    state: null
    internalState: null
    __proto__: CompositeLayer
  length: 1
  __proto__: Array(0)
  mapStyle: "mapbox://styles/mapbox/light-v9"
views: Array(1)
  0: null
  length: 1
  __proto__: Array(0)
__proto__: Object
```

That object has async properties which I believe are not being correctly handled by the React Deck.GL component.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.11
 - Browser Version: Chrome 79
